### ISSUE TITLE
Add a home page. 

### ISSUE THREAD

**Issue by morelmiles** [devckla/devckla.github.io#33]
I'd like to: 
1. Add a home page with a hero image. 
2. Add more links to the navbar and add more pages.
The pages to be added include: 
- Events 
- Community Leads (The team) 
- Communities for example PyLadies, GDG
3. Add the ```required``` flag to the input elements so as to validate the input information by the user. 
4. Add an option for toggling between dark and light modes.

**Comment by Emmanuel-Melon** [comment]
@morelmiles Absolutely, this sounds really amazing! I think you should totally go for it!

**Comment by morelmiles** [comment]
Will get onto it.
